### ISSUE TITLE
UI is breaking when shipped with exe file. And transferred to another machine

### ISSUE THREAD

**Issue by manknak** [sangnak/Blastoserve_camera#15]
folder structure containing .exe file was shared  by @AbhaySatpute  with me yesterday 
and we tried running that on following systems

- OS:- windows 7
- Browser:- mozilla firefox

But UI was breaking to the specific all the components were misplaced everything was left aligned

@AbhaySatpute  can you please update UI screen shot that we tested in comments

But functionality was running fine.

Earlier we tried running exe from zip application and we thought UI is breaking because dependencies are still in zip. So we tried running . exe after unzipping the files but no luck

**Comment by manknak** [comment]
https://user-images.githubusercontent.com/100838198/162570009-4a86b69e-2a68-4b10-9518-884dd31f13ae.mp4

**Comment by manknak** [comment]
This is the video that is shared with us from hospital

**Comment by tejasvaij2204** [comment]
![Running with css properly](https://user-images.githubusercontent.com/101651283/162629273-7633ed6a-a9a8-40e3-bbfe-4f75e0592e9a.PNG)

UI is running with css in my pc (windows 7 os VM) but this same form filling page is seen after submitting.

**Comment by tejasvaij2204** [comment]
https://user-images.githubusercontent.com/101651283/162629654-55f873a9-9742-4f40-9b9c-d2e1b968f49f.mp4

css working as expected with the new code, where we downloaded the bootstrap css and imported its link in html file
